Lydia/rs 16 error tracking with sentry
danielpaul/rails-starter pull request #25
Opened 2023-06-06 11:47 UTC by LydiaKoil

2023-06-06 12:39 UTC, danielpaul requested changes

2023-06-06 12:39 UTC, danielpaul commented on app/controllers/application_controller.rb
> +  def set_sentry_user
this method isn't getting called from anywhere?

2023-06-06 12:39 UTC, danielpaul commented on app/controllers/application_controller.rb
> +  def set_sentry_user
https://github.com/IdentitySquare/IntergalacticFootball/blob/c99fabd4938735beb49390ffc2c4e5cafaaab61a/app/controllers/application_controller.rb#L11

2023-06-06 12:39 UTC, danielpaul commented on app/views/layouts/components/_head.html.haml
> +        dsn: SENTRY_DSN_JS,
the value also need to be inside `""` and not just printed when its displayed. the output should be the same as what you would expect if the value was hard coded here. have a look at the output HTML to confirm.

2023-06-09 11:08 UTC, LydiaKoil commented on app/views/layouts/components/_head.html.haml
> +        dsn: SENTRY_DSN_JS,
<img width="440" alt="image" src="https://github.com/danielpaul/rails-starter/assets/47219609/cc172c89-208a-4849-9249-07f8ad91ab00">

2023-06-10 09:08 UTC, danielpaul approved these changes

2023-06-10 11:24 UTC, merged